version: '2'

services:
  app:
    image: ghcr.io/jetbrains-research/bus-factor-explorer/bus-factor-explorer:0.0.1
    container_name: app
    ports:
      - 8080:8080
      - 8090:8090 # Metrics
    volumes:
      - ./compose-workdir/:/root
    environment:
      PORT: 8080
      JAVA_TOOL_OPTIONS: "-Xms256M -Xmx10G"
      GH_TOKEN: ""
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./compose-workdir/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./compose-workdir/prometheus:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000

