name: Java CI with Gradle
on: ["push"]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Check GitHub workflows files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
      - name: Lint kotlin
        run: ./gradlew ktlintCheck
      - name: Test
        run: ./gradlew test
